# Generated by Django 5.1.3 on 2024-11-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='looking_for',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='requirements',
            field=models.TextField(blank=True),
        ),
    ]
