# Generated by Django 5.1.4 on 2024-12-17 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_teaminvite_delete_teaminvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminvite',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 24, 18, 11, 15, 91651, tzinfo=datetime.timezone.utc)),
        ),
    ]
