# Generated by Django 5.1.4 on 2024-12-17 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_alter_teaminvite_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminvite',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 24, 18, 17, 28, 182035, tzinfo=datetime.timezone.utc)),
        ),
    ]
